#!/usr/bin/env python
from devices import imu

class dummysource():
    def __init__(self): pass
    def data(self): return {'rawacc': [0,0,0]}

s = dummysource()
i = imu.IMU(s)
i.read_sensor('ADIS')
